theme: jekyll-theme-minimal
logo: /assets/teru_priere_portrait_850x1180.png
title: Priere's DevLog
description: My personal website and project showcase.
show_downloads: false
gallery_url: /assets/gallery/
collections:
  projects:
    output: false
include: ['.well-known']
