theme: jekyll-theme-minimal
logo: /assets/nyam_headshot_300x300.png
title: Priere's DevLog
description: Welcome to my website!
show_downloads: false
collections:
    projects:
        output: false
include: ['.well-known']
